version: '3'

# dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  build:
    desc: build the container
    cmds:
      - docker build --progress=plain -t "redditpostnotification" ./
    sources:
      - src/**/**
      - requirements*.txt
      - config.yml
      - Dockerfile
      - Taskfile.yml

  run:
    desc: run the script in the container
    deps: [build]
    cmds:
      - docker run redditpostnotification

#  test:
#    desc: run the unit tests
#    deps: [build]
#    cmds:
#      - go test -v ./...
#
#  lint:
#    desc: Runs golangci-lint
#    sources:
#      - './**/*.go'
#      - .golangci.yml
#    cmds:
#      - golangci-lint run
