version: '3'

tasks:
  default:
    cmds:
      - task --list

  build:
    desc: build the container
    cmds:
      - docker build --tag redditpostnotification .
    sources:
      - src/**/**
      - test/**/**
      - do/**/**
      - requirements*.txt
      - .*rc
      - Dockerfile
      - config.yml
      - Taskfile.yml

  run:
    desc: start program in the container
    deps: [build]
    cmds:
      - docker run redditpostnotification

  test:
    desc: run tests in the container and report coverage
    deps: [build]
    cmds:
      - docker run --entrypoint '/bin/sh' redditpostnotification -c "./do/test.sh"

  lint:
    desc: lint the codebase
    deps: [build]
    cmds:
      - docker run --entrypoint '/bin/sh' redditpostnotification -c "./do/lint.sh"
