version: '3'

# dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  build:
    desc: build the container
    cmds:
      - docker build --tag "redditpostnotification" ./
    sources:
      - src/**/**
      - requirements*.txt
      - config.yml
      - Dockerfile
      - Taskfile.yml
      - do/**/**
      - .pylintrc
      - .coveragerc

  run:
    desc: run the script in the container
    deps: [build]
    cmds:
      - docker run redditpostnotification

  test:
    desc: run tests in the container
    deps: [build]
    cmds:
      - docker run --entrypoint '/bin/sh' redditpostnotification -c "pytest"

  lint:
    desc: run lint script
    deps: [build]
    cmds:
      - docker run --entrypoint '/bin/sh' redditpostnotification -c "./do/lint.sh"
