#!/bin/bash

# THIS IS NOT CURRENTLY BEING USED OR SUPPORTED

# moves RedditPostNotification to /bin, where it will be ran upon the start of the raspberry pi

#TODO: add script to path, test, and ship
# https://stackoverflow.com/questions/24518522/run-python-script-at-startup-in-ubuntu
# https://askubuntu.com/questions/8653/how-to-keep-processes-running-after-ending-ssh-session

if [ -d "/bin/RedditPostNotification" ]; # if the directory exists
then
	cd /bin/RedditPostNotification # navigate to where script is stored
	find . -type f ! -name '*.log' -delete # delete every file in directory except the logs
	sudo cp -r ~/RedditPostNotification/. /bin/RedditPostNotification/ # copies updated script's contents into where script resides
else
	sudo cp -r ~/RedditPostNotification /bin # copy the script's directory to /bin 
fi
