name: Build
on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup task
        uses: arduino/setup-task@v2
        with:
          version: 3.34.1

      - name: build
        run: task build

      - name: lint
        run: task lint

      - name: test
        run: task test
