name: Unit Tests
on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: coverage run -m pytest

      - name: Run coverage
        run: coverage report --fail-under=40  # todo pump this rookie number up

      - name: Run pylint
        run: pylint ./tests ./src
